# Generated by Django 3.0.7 on 2020-06-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('academic_degree', models.CharField(choices=[('Specialist', 'Spe.'), ('Master', 'Me.'), ('Doctor', 'Dr.')], max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('matriculation', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('coorientator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_coorientator', to='core.Teacher')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_leader', to='core.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=1000)),
                ('type_project', models.CharField(choices=[('TCC', 'TCC'), ('TCC1', 'TCC1'), ('TCC2', 'TCC2')], max_length=200)),
                ('defense_model', models.CharField(choices=[('Monography', 'Monography'), ('Article', 'Article'), ('SoftwareReport', 'Software Report'), ('Others', 'Others')], max_length=200)),
                ('name_student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_date', models.DateField()),
                ('expected_time', models.TimeField()),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Confirmada', 'Confirmada'), ('Concluida', 'Concluida')], max_length=200)),
                ('course_coordinator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Teacher')),
                ('member', models.ManyToManyField(related_name='examinationboard_member', to='core.Teacher')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Student')),
            ],
        ),
    ]
